cache: apt

language: go
go:
  - tip
  - 1.5.2
  - 1.5.1
  - 1.5
  - 1.4.3
  - 1.4.2
  - 1.4.1
  - 1.4
  - 1.3.3
  - 1.3.2
  - 1.3.1
  - 1.3

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get -t -v ./...

script:
  - go test -coverprofile=bqstreamer.coverprofile ./

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci
